<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_indo_model extends CI_Model
{

    public $table = 'nilai_indo';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_query(){
        $sql = "SELECT s.id, m.nama, s.ulangan, s.uts, s.uas
                FROM nilai_indo as s, siswa as m 
                WHERE s.id = m.id";
        return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('ulangan', $q);
	$this->db->or_like('uts', $q);
	$this->db->or_like('uas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('ulangan', $q);
	$this->db->or_like('uts', $q);
	$this->db->or_like('uas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Nilai_indo_model.php */
/* Location: ./application/models/Nilai_indo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-05 20:13:02 */
/* http://harviacode.com */